# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check quality of sql code

on: pull_request

jobs:
  sqlcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: yokawasa/action-sqlcheck@v1.3.0
      id: sqlcheck
      with:
        post-comment: true
        risk-level: 1
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get output
      run: echo "Issues found in previous step"
      if: steps.sqlcheck.outputs.issue-found

